version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    network_mode: host
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    build: ./backend/foodgram_backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    container_name: infra
    build: infra/
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 8000:80
    depends_on:
      - frontend