# Generated by Django 3.2.16 on 2024-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240521_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Список избранных рецептов', 'verbose_name_plural': 'Списки избранных рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Составы Рецептов'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'verbose_name': 'Корзину покупок', 'verbose_name_plural': 'Корзины покупок'},
        ),
    ]
