# Generated by Django 4.2.13 on 2024-05-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Короткая ссылка')),
                ('full_url', models.CharField(max_length=500, verbose_name='Полная ссылка')),
            ],
            options={
                'verbose_name': 'короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
                'db_table': 'shortlink',
            },
        ),
    ]
