# Generated by Django 4.2.13 on 2024-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortlink_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('id',), 'verbose_name': 'короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
    ]
