# Generated by Django 4.2.13 on 2024-05-30 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_amount_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления - 1 мин.'), django.core.validators.MaxValueValidator(32000, message='Максимальное время приготовления - 32000 мин.')], verbose_name='Время приготовления, мин.'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Рецепт должен состоять минимум из 1 ингридиента(-ов).'), django.core.validators.MaxValueValidator(32000, message='Рецепт должен состоять максимум из 32000 ингридиентов.')], verbose_name='Количество'),
        ),
    ]
